# Data Science Course Week 1 - Data Manipulation using Pandas

## Here we will be using real data sources to explore the features of Pandas


In [12]:
import pandas as pd

# Class Workshop

## Numpy Overview

* Why Python for Data? Numpy brings *decades* of C math into Python!
* Numpy provides a wrapper for extensive C/C++/Fortran codebases, used for data analysis functionality
* NDAarray allows easy vectorized math and broadcasting (i.e. functions for vector elements of different shapes)

In [13]:
import numpy as np

### Creating ndarrays
An array object represents a multidimensional, homogeneous array of fixed-size items.

In [4]:
a = np.array( [20,30,40,50] )
b = np.arange( 4 )
b

array([0, 1, 2, 3])

In [10]:
?np.random.randint

In [6]:
c = a-b
c

array([20, 29, 38, 47])

In [7]:
b**2

array([0, 1, 4, 9])

In [9]:
# Creating arrays
a = np.zeros((3))
b = np.ones((2,3))
c = np.random.randint(1,10,(2,3,4))

In [11]:
a

array([ 0.,  0.,  0.])

In [10]:
b

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [11]:
c

array([[[9, 8, 1, 1],
        [1, 1, 7, 7],
        [5, 4, 8, 8]],

       [[8, 8, 3, 7],
        [9, 9, 8, 5],
        [3, 4, 3, 9]]])

## Indexing, Slicing and Iterating

In [12]:
# one-dimensional arrays work like lists:
a = np.arange(10)**2

In [13]:
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [14]:
a[2:5]

array([ 4,  9, 16])

In [15]:
a[0:3]

array([0, 1, 4])

In [16]:
a[1:3]

array([1, 4])

### Reading Files, Selecting Columns, and Summarizing

MovieLens 100k movie rating data:
    main page: http://grouplens.org/datasets/movielens/
    data dictionary: http://files.grouplens.org/datasets/movielens/ml-100k-README.txt
    files: u.user, u.data, u.item

In [19]:
# can read a file from local computer or directly from a URL
pd.read_table('u.user', header=None)

0
0         1|24|M|technician|85711
1              2|53|F|other|94043
2             3|23|M|writer|32067
3         4|24|M|technician|43537
4              5|33|F|other|15213
5          6|42|M|executive|98101
6      7|57|M|administrator|91344
7      8|36|M|administrator|05201
8            9|29|M|student|01002
9            10|53|M|lawyer|90703
10            11|39|F|other|30329
11            12|28|F|other|06405
12         13|47|M|educator|29206
13        14|45|M|scientist|55106
14         15|49|F|educator|97301
15    16|21|M|entertainment|10309
16       17|30|M|programmer|06355
17            18|35|F|other|37212
18        19|40|M|librarian|02138
19        20|42|F|homemaker|95660
20           21|26|M|writer|30068
21           22|25|M|writer|40206
22           23|30|F|artist|48197
23           24|21|F|artist|94533
24         25|39|M|engineer|55107
25         26|49|M|engineer|21044
26        27|40|F|librarian|30030
27           28|32|M|writer|55369
28       29|41|M|programmer|94043
29           30|7|M|student|55436
..                            ...
913          914|44|F|other|08105
914  915|50|M|entertainment|60614
915       916|27|M|engineer|N2L5N
916        917|22|F|student|20006
917      918|40|M|scientist|70116
918          919|25|M|other|14216
919         920|30|F|artist|90008
920        921|20|F|student|98801
921  922|29|F|administrator|21114
922        923|21|M|student|E2E3R
923          924|29|M|other|11753
924       925|18|F|salesman|49036
925  926|49|M|entertainment|01701
926     927|23|M|programmer|55428
927        928|21|M|student|55408
928      929|44|M|scientist|53711
929      930|28|F|scientist|07310
930       931|60|M|educator|33556
931       932|58|M|educator|06437
932        933|28|M|student|48105
933       934|61|M|engineer|22902
934         935|42|M|doctor|66221
935          936|24|M|other|32789
936       937|48|M|educator|98072
937     938|38|F|technician|55038
938        939|26|F|student|33319
939  940|32|M|administrator|02215
940        941|20|M|student|97229
941      942|48|F|librarian|78209
942        943|22|M|student|77841

[943 rows x 1 columns]

Now having seen the data, read it in again but now with the pipe separator/delimiter.

In [27]:
# read 'u.user' and asign to 'users' so that we can re-use the data
user_cols = ['user_id', 'age', 'gender', 'occupation', 'zip_code']
users = pd.read_table('u.user', sep='|', header=None, names=user_cols, index_col='user_id', dtype={'zip_code':str})

Now try running the example code below, uncommenting each line one at a time to see what results

In [60]:
# examine the users data

#users                   # print the first 30 and last 30 rows
#type(users)             # DataFrame
#users.head()            # print the first 5 rows
#users.head(10)          # print the first 10 rows
#users.tail()            # print the last 5 rows
#users.index             # "the index" (aka "the labels")
#users.columns           # column names (which is "an index")
#users.dtypes            # data types of each column
#users.shape             # number of rows and columns
#users.values            # underlying numpy array
#users.info()            # concise summary (including memory usage)

Index(['age', 'gender', 'occupation', 'zip_code'], dtype='object')

Now try some of the different methods for selecting a column from a dataframe by name.

In [30]:
# select a column

#users['gender']         # select one column
#type(users['gender'])   # Series
#users[['gender']]
#type(users[['gender']])   # DataFrame
#users.gender            # select one column using the DataFrame attribute


user_id
1      M
2      F
3      M
4      M
5      F
6      M
7      M
8      M
9      M
10     M
11     F
12     F
13     M
14     M
15     F
16     M
17     M
18     F
19     M
20     F
21     M
22     M
23     F
24     F
25     M
26     M
27     F
28     M
29     M
30     M
      ..
914    F
915    M
916    M
917    F
918    M
919    M
920    F
921    F
922    F
923    M
924    M
925    F
926    M
927    M
928    M
929    M
930    F
931    M
932    M
933    M
934    M
935    M
936    M
937    M
938    F
939    F
940    M
941    M
942    F
943    M
Name: gender, dtype: object

Now try some built in pandas methods for producing summary descriptive information from a dataframe.

In [35]:
# summarize (describe) the data

#users.describe()                    # describe all numeric columns
#users.describe(include=['object'])  # describe all object columns (can include multiple types)
#users.describe(include='all')       # describe all columns
#users.gender.describe()             # describe a single column
#users.age.mean()                    # only calculate the mean


34.05196182396607

In [37]:
# count the number of occurrences of each value
#users.occupation.value_counts()     # most useful for categorical variables
#users.age.value_counts()        # can also be used with numeric variables

30    39
25    38
22    37
28    36
27    35
26    34
24    33
29    32
20    32
32    28
23    28
35    27
21    27
33    26
31    25
19    23
44    23
39    22
40    21
36    21
42    21
51    20
50    20
48    20
49    19
37    19
18    18
34    17
38    17
45    15
      ..
47    14
43    13
46    12
53    12
55    11
41    10
57     9
60     9
52     6
56     6
15     6
13     5
16     5
54     4
63     3
14     3
65     3
70     3
61     3
59     3
58     3
64     2
68     2
69     2
62     2
11     1
10     1
73     1
66     1
7      1
Name: age, dtype: int64

# Student Exercises

## Excercise One

### Data

WHO alcohol consumption data:
    article: http://fivethirtyeight.com/datalab/dear-mona-followup-where-do-people-drink-the-most-beer-wine-and-spirits/    
    original data: https://github.com/fivethirtyeight/data/tree/master/alcohol-consumption
    file: drinks.csv (with additional 'continent' column)


In [25]:
# read drinks.csv into a DataFrame called 'drinks'
drinks = pd.read_table('drinks.csv', sep=',')
#drinks = pd.read_table('drinks.csv', header=None)
#assign header
#user_cols = ['country', 'beer_servings', 
 #          'spirit_servings', 'wine_servings', 'total_litres_of_pure_alcohol', 'continent']
#drinks = pd.read_table('drinks.csv', sep=',', header=None, names=user_cols, index_col='country')
drinks = pd.read_csv('drinks.csv')              # assumes separator is comma

In [128]:
# print the head and the tail
#drinks
#drinks.head()
#drinks.tail()

country  beer_servings  spirit_servings  wine_servings  \
0  Afghanistan              0                0              0   
1      Albania             89              132             54   
2      Algeria             25                0             14   
3      Andorra            245              138            312   
4       Angola            217               57             45   

   total_litres_of_pure_alcohol continent  
0                           0.0        AS  
1                           4.9        EU  
2                           0.7        AF  
3                          12.4        EU  
4                           5.9        AF

In [129]:
# examine the default index, data types, and shape
#drinks.index
#drinks.dtypes
drinks.shape

(193, 6)

In [130]:
# print the 'beer_servings' Series
drinks['beer_servings']
drinks.beer_servings


0        0
1       89
2       25
3      245
4      217
5      102
6      193
7       21
8      261
9      279
10      21
11     122
12      42
13       0
14     143
15     142
16     295
17     263
18      34
19      23
20     167
21      76
22     173
23     245
24      31
25     231
26      25
27      88
28      37
29     144
      ... 
163    128
164     90
165    152
166    185
167      5
168      2
169     99
170    106
171      1
172     36
173     36
174    197
175     51
176     51
177     19
178      6
179     45
180    206
181     16
182    219
183     36
184    249
185    115
186     25
187     21
188    333
189    111
190      6
191     32
192     64
Name: beer_servings, dtype: int64

In [86]:
# calculate the average 'beer_servings' for the entire dataset
#drinks.describe()                   # summarize all numeric columns
#drinks.beer_servings.describe()     # summarize only the 'beer_servings' Series
#drinks.beer_servings.mean()         # only calculate the mean


106.16062176165804

In [131]:

# count the number of occurrences of each 'continent' value and see if it looks correct
drinks.continent.value_counts()


AF    53
EU    45
AS    44
OC    16
SA    12
Name: continent, dtype: int64

#### Filtering and Sorting

using users data set again

In [1]:
# logical filtering: only show users with age < 20
#young_bool = users.age < 20         # create a Series of booleans...
#users[young_bool]                   # ...and use that Series to filter rows
#users[users.age < 20]               # or, combine into a single step
#users[users.age < 20].occupation    # select one column from the filtered results
#users[users.age < 20].occupation.value_counts()     # value_counts of resulting Series

NameError: name 'users' is not defined

In [102]:
# logical filtering with multiple conditions
#users[(users.age < 20) & (users.gender=='M')]       # ampersand for AND condition
#users[(users.age < 20) | (users.age > 60)]          # pipe for OR condition
#users[users.occupation.isin(['doctor', 'lawyer'])]  # alternative to multiple OR conditions


age gender     occupation zip_code
user_id                                    
30         7      M        student    55436
57        16      M           none    84010
67        17      M        student    60402
68        19      M        student    22904
101       15      M        student    05146
110       19      M        student    77840
142       13      M          other    48118
179       15      M  entertainment    20755
221       19      M        student    20685
246       19      M        student    28734
257       17      M        student    77005
289       11      M           none    94619
291       19      M        student    44106
303       19      M        student    14853
320       19      M        student    24060
347       18      M        student    90210
367       17      M        student    37411
368       18      M        student    92113
375       17      M  entertainment    37777
393       19      M        student    83686
397       17      M        student    27514
425       19      M        student    58644
451       16      M        student    48446
453       18      M        student    06333
461       15      M        student    98102
471       10      M        student    77459
521       19      M        student    02146
528       18      M        student    55104
580       16      M        student    17961
582       17      M        student    93003
592       18      M        student    97520
619       17      M        student    44134
621       17      M        student    60402
624       19      M        student    30067
628       13      M           none    94306
632       18      M        student    55454
700       17      M        student    76309
710       19      M        student    92020
729       19      M        student    56567
747       19      M          other    93612
761       17      M        student    97302
817       19      M        student    60152
851       18      M          other    29646
863       17      M        student    60089
880       13      M        student    83702

In [146]:
# sorting

#users.age.sort_values()                   # sort a column
#users.sort_values(by='age')                   # sort a DataFrame by a single column
users.sort_values(by='age', ascending=False)  # use descending order instead
#users.sort_values(by=['occupation', 'age'])   # sort by multiple columns


age gender     occupation zip_code
user_id                                    
481       73      M        retired    37771
803       70      M  administrator    78212
767       70      M       engineer    00000
860       70      F        retired    48322
585       69      M      librarian    98501
559       69      M      executive    10022
349       68      M        retired    61455
573       68      M        retired    48911
211       66      M       salesman    32605
651       65      M        retired    02903
564       65      M        retired    94591
318       65      M        retired    06518
845       64      M         doctor    97405
423       64      M          other    91606
858       63      M       educator    09645
364       63      M       engineer    01810
777       63      M     programmer    01810
266       62      F  administrator    78756
520       62      M     healthcare    12603
934       61      M       engineer    22902
351       61      M       educator    49938
106       61      M        retired    55125
464       60      M         writer    94583
469       60      M       educator    78628
234       60      M        retired    94702
900       60      M        retired    18505
308       60      M        retired    95076
931       60      M       educator    33556
694       60      M     programmer    06365
752       60      M        retired    21201
...      ...    ...            ...      ...
700       17      M        student    76309
646       17      F        student    51250
863       17      M        student    60089
375       17      M  entertainment    37777
761       17      M        student    97302
621       17      M        student    60402
257       17      M        student    77005
904       17      F        student    61073
434       16      F        student    49705
451       16      M        student    48446
550       16      F        student    95453
57        16      M           none    84010
580       16      M        student    17961
179       15      M  entertainment    20755
461       15      M        student    98102
618       15      F        student    44212
849       15      F        student    25652
281       15      F        student    06059
101       15      M        student    05146
813       14      F        student    02136
887       14      F        student    27249
206       14      F        student    53115
628       13      M           none    94306
674       13      F        student    55337
142       13      M          other    48118
880       13      M        student    83702
609       13      F        student    55106
289       11      M           none    94619
471       10      M        student    77459
30         7      M        student    55436

[943 rows x 4 columns]

## Excercise Two

using the drinks dataset again and refering to the code demonstrated above, write code to answer these questions:

In [133]:
# filter DataFrame to only include European countries
drinks[drinks.continent == 'EU']

country  beer_servings  spirit_servings  wine_servings  \
1               Albania             89              132             54   
3               Andorra            245              138            312   
7               Armenia             21              179             11   
9               Austria            279               75            191   
10           Azerbaijan             21               46              5   
15              Belarus            142              373             42   
16              Belgium            295               84            212   
21   Bosnia-Herzegovina             76              173              8   
25             Bulgaria            231              252             94   
42              Croatia            230               87            254   
44               Cyprus            192              154            113   
45       Czech Republic            361              170            134   
48              Denmark            224               81            278   
57              Estonia            224              194             59   
60              Finland            263              133             97   
61               France            127              151            370   
64              Georgia             52              100            149   
65              Germany            346              117            175   
67               Greece            133              112            218   
75              Hungary            234              215            185   
76              Iceland            233               61             78   
81              Ireland            313              118            165   
83                Italy             85               42            237   
93               Latvia            281              216             62   
98            Lithuania            343              244             56   
99           Luxembourg            236              133            271   
105               Malta            149              100            120   
111              Monaco              0                0              0   
113          Montenegro             31              114            128   
120         Netherlands            251               88            190   
126              Norway            169               71            129   
135              Poland            343              215             56   
136            Portugal            194               67            339   
139             Moldova            109              226             18   
140             Romania            297              122            167   
147          San Marino              0                0              0   
151              Serbia            283              131            127   
155            Slovakia            196              293            116   
156            Slovenia            270               51            276   
160               Spain            284              157            112   
165              Sweden            152               60            186   
166         Switzerland            185              100            280   
170           Macedonia            106               27             86   
180             Ukraine            206              237             45   
182      United Kingdom            219              126            195   

     total_litres_of_pure_alcohol continent  
1                             4.9        EU  
3                            12.4        EU  
7                             3.8        EU  
9                             9.7        EU  
10                            1.3        EU  
15                           14.4        EU  
16                           10.5        EU  
21                            4.6        EU  
25                           10.3        EU  
42                           10.2        EU  
44                            8.2        EU  
45                           11.8        EU  
48           

In [135]:
# filter DataFrame to only include European countries with wine_servings > 300
drinks[(drinks.continent == 'EU') & (drinks.wine_servings > 300)]

country  beer_servings  spirit_servings  wine_servings  \
3     Andorra            245              138            312   
61     France            127              151            370   
136  Portugal            194               67            339   

     total_litres_of_pure_alcohol continent  
3                            12.4        EU  
61                           11.8        EU  
136                          11.0        EU

In [136]:
# calculate the average 'beer_servings' for all of Europe
 drinks[drinks.continent == 'EU'].beer_servings.mean() 

193.77777777777777

In [148]:
# determine which 10 countries have the highest total_litres_of_pure_alcohol
drinks.sort_values(by='total_litres_of_pure_alcohol', ascending=False)

country  beer_servings  spirit_servings  wine_servings  \
15              Belarus            142              373             42   
98            Lithuania            343              244             56   
3               Andorra            245              138            312   
68              Grenada            199              438             28   
45       Czech Republic            361              170            134   
61               France            127              151            370   
141  Russian Federation            247              326             73   
81              Ireland            313              118            165   
155            Slovakia            196              293            116   
99           Luxembourg            236              133            271   
65              Germany            346              117            175   
75              Hungary            234              215            185   
136            Portugal            194               67            339   
135              Poland            343              215             56   
156            Slovenia            270               51            276   
93               Latvia            281              216             62   
16              Belgium            295               84            212   
48              Denmark            224               81            278   
182      United Kingdom            219              126            195   
140             Romania            297              122            167   
8             Australia            261               72            212   
25             Bulgaria            231              252             94   
166         Switzerland            185              100            280   
42              Croatia            230               87            254   
144           St. Lucia            171              315             71   
60              Finland            263              133             97   
160               Spain            284              157            112   
138         South Korea            140               16              9   
9               Austria            279               75            191   
151              Serbia            283              131            127   
..                  ...            ...              ...            ...   
114             Morocco             12                6             10   
19               Bhutan             23                0              0   
34                 Chad             15                1              1   
102            Malaysia             13                4              0   
168          Tajikistan              2               15              0   
150             Senegal              9                1              7   
70               Guinea              9                0              2   
80                 Iraq              9                3              0   
53                Egypt              6                4              1   
119               Nepal              5                6              0   
149        Saudi Arabia              0                5              0   
78            Indonesia              5                1              0   
116             Myanmar              5                1              0   
190               Yemen              6                0              0   
123               Niger              3                2              1   
171         Timor-Leste              1                1              4   
38              Comoros              1                3              1   
13           Bangladesh              0                0              0   
107          Mauritania              0                0              0   
111              Monaco              0                0              0   
103            Maldives              0                0              0   
106    Marshall Islands              0                0              0   
46          North Ko

# Optional Excercises

### Merging Data

In [15]:
# read 'u.item' into 'movies'
#movie_cols = ['movie_id', 'title']
#movies = pd.read_table('u.item', sep='|', header=None, names=movie_cols, usecols=[0, 1])


In [17]:
# read 'u.data' into 'ratings'
#rating_cols = ['user_id', 'movie_id', 'rating', 'timestamp']
#ratings = pd.read_table('u.data', sep='\t', header=None, names=rating_cols)

In [20]:
# merge 'movies' and 'ratings' (inner join on 'movie_id')
movie_ratings = pd.merge(movies, ratings)
#movies.shape
#ratings.shape
movie_ratings.shape

(100000, 5)

### Grouping Data

In [21]:
movie_ratings.columns

Index(['movie_id', 'title', 'user_id', 'rating', 'timestamp'], dtype='object')

In [22]:
movie_ratings[['title', 'rating']].groupby('title').sum()

rating
title                                                     
'Til There Was You (1997)                               21
1-900 (1994)                                            13
101 Dalmatians (1996)                                  317
12 Angry Men (1957)                                    543
187 (1997)                                             124
2 Days in the Valley (1996)                            300
20,000 Leagues Under the Sea (1954)                    252
2001: A Space Odyssey (1968)                          1028
3 Ninjas: High Noon At Mega Mountain (1998)              5
39 Steps, The (1935)                                   239
8 1/2 (1963)                                           145
8 Heads in a Duffel Bag (1997)                          13
8 Seconds (1994)                                        15
A Chef in Love (1996)                                   33
Above the Rim (1994)                                    15
Absolute Power (1997)                                  428
Abyss, The (1989)                                      542
Ace Ventura: Pet Detective (1994)                      314
Ace Ventura: When Nature Calls (1995)                   99
Across the Sea of Time (1995)                           11
Addams Family Values (1993)                            245
Addicted to Love (1997)                                171
Addiction, The (1995)                                   24
Adventures of Pinocchio, The (1996)                    119
Adventures of Priscilla, Queen of the Desert, T...     399
Adventures of Robin Hood, The (1938)                   254
Affair to Remember, An (1957)                          109
African Queen, The (1951)                              636
Afterglow (1997)                                        56
Age of Innocence, The (1993)                           220
...                                                    ...
Window to Paris (1994)                                   4
Wings of Courage (1995)                                  4
Wings of Desire (1987)                                 228
Wings of the Dove, The (1997)                          276
Winnie the Pooh and the Blustery Day (1968)            285
Winter Guest, The (1997)                                31
Wishmaster (1997)                                       66
With Honors (1994)                                     141
Withnail and I (1987)                                   42
Witness (1985)                                           4
Wizard of Oz, The (1939)                              1003
Wolf (1994)                                            181
Woman in Question, The (1950)                            1
Women, The (1939)                                       55
Wonderful, Horrible Life of Leni Riefenstahl, T...      40
Wonderland (1997)                                       32
Wooden Man's Bride, The (Wu Kui) (1994)                  8
World of Apu, The (Apur Sansar) (1959)                  24
Wrong Trousers, The (1993)                             527
Wyatt Earp (1994)                                      155
Yankee Zulu (1994)                                       1
Year of the Horse (1997)                                23
You So Crazy (1994)                                      3
Young Frankenstein (1974)                              789
Young Guns (1988)                                      324
Young Guns II (1990)                                   122
Young Poisoner's Handbook, The (1995)                  137
Zeus and Roxanne (1997)                                 13
unknown                                                 31
Á köldum klaka (Cold Fever) (1994)                       3

[1664 rows x 1 columns]

### Handling Missing Values

In [31]:
# missing values are usually excluded by default
#drinks.continent.value_counts()              # excludes missing values
drinks.continent.value_counts(dropna=False)  # includes missing values

AF     53
EU     45
AS     44
NaN    23
OC     16
SA     12
Name: continent, dtype: int64

In [45]:
# find missing values in a Series
#drinks.continent.isnull()           # True if missing, False if not missing
drinks.continent.isnull().sum()     # count the missing values
#drinks.continent.notnull()          # True if not missing, False if missing
#drinks[drinks.continent.notnull()]  # only show rows where continent is not missing

23

In [36]:
# use 'tilde' ~ to negate the boolean values
drinks.continent.isnull()  

0      False
1      False
2      False
3      False
4      False
5       True
6      False
7      False
8      False
9      False
10     False
11      True
12     False
13     False
14      True
15     False
16     False
17      True
18     False
19     False
20     False
21     False
22     False
23     False
24     False
25     False
26     False
27     False
28     False
29     False
       ...  
163    False
164    False
165    False
166    False
167    False
168    False
169    False
170    False
171    False
172    False
173    False
174     True
175    False
176    False
177    False
178    False
179    False
180    False
181    False
182    False
183    False
184     True
185    False
186    False
187    False
188    False
189    False
190    False
191    False
192    False
Name: continent, dtype: bool

In [41]:
# side note: understanding axes
#drinks.sum(axis=0)      # sums "down" the 0 axis (rows)
#drinks.sum()            # axis=0 is the default
#drinks.sum(axis=1)      # sums "across" the 1 axis (columns)

0        0.0
1      279.9
2       39.7
3      707.4
4      324.9
5      279.9
6      447.3
7      214.8
8      555.4
9      554.7
10      73.3
11     355.3
12     114.0
13       0.0
14     358.3
15     571.4
16     601.5
17     391.8
18      52.1
19      23.4
20     219.8
21     261.6
22     248.4
23     413.2
24      34.6
25     587.3
26      43.3
27      94.3
28      49.0
29     220.0
       ...  
163    318.6
164     98.7
165    405.2
166    575.2
167     57.0
168     17.3
169    364.4
170    222.9
171      6.1
172     58.3
173     63.1
174    366.4
175     75.3
176     81.4
177    124.2
178     57.0
179     62.3
180    496.9
181    158.8
182    550.4
183     48.7
184    499.7
185    376.6
186    136.4
187     50.9
188    443.7
189    116.0
190      6.1
191     57.5
192     90.7
dtype: float64

In [43]:
# find missing values in a DataFrame
#drinks.isnull()             # DataFrame of booleans
#drinks.isnull().sum()       # count the missing values in each column

country                          0
beer_servings                    0
spirit_servings                  0
wine_servings                    0
total_litres_of_pure_alcohol     0
continent                       23
dtype: int64

In [47]:
# fill in missing values
#drinks.continent.fillna(value='NA')                 # fill in missing values with 'NA'
drinks.continent.fillna(value='NA', inplace=True)   # modifies 'drinks' in-place